# Version 2 pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}

  initContainers:
    - name: init-container
      image: busybox
      command: ['sh', '-c', 'echo "<h1>Homework Page</h1>" > /init/index.html']
      volumeMounts:
        - name: shared-volume
          mountPath: /init

  containers:
    - name: web-server
      image: nginx:alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-volume
          mountPath: /usr/share/nginx/html
      command: ["nginx"]
      args: ["-g", "daemon off;"]
      lifecycle:
        preStop:
          exec:
            command: ["rm", "-f", "/usr/share/nginx/html/index.html"]
